import SharedFoodAPI from "./components/FoodsComponents/SharedFoodAPI";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "LinuBayo Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
          <div id="modal-hook"></div>
          <div id="backdrop-hook"></div>
          <div id="root"></div>
          {children}
        </main>
        {/* <SharedFoodAPI /> */}
      </body>
    </html>
  );
}
