import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "LinuBayo Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div id="modal-hook"></div>
        <div id="backdrop-hook"></div>
        <div id="root"></div>
        {children}
      </body>
    </html>
  );
}
